import IISOperacionnoe_podrazdelenieОткрытиеСчетаEController from '../i-i-s-operacionnoe-podrazdelenie-открытие-счета-e';

var IISOperacionnoe_podrazdelenieОткрытиеСчетаENewController = IISOperacionnoe_podrazdelenieОткрытиеСчетаEController;
export default IISOperacionnoe_podrazdelenieОткрытиеСчетаENewController;
