//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Operacionnoe_podrazdelenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Закрытие счета.
    /// </summary>
    // *** Start programmer edit section *** (ЗакрытиеСчета CustomAttributes)

    // *** End programmer edit section *** (ЗакрытиеСчета CustomAttributes)
    [AutoAltered()]
    [Caption("Закрытие счета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗакрытиеСчетаE", new string[] {
            "ДатаЗакрСчета as \'Дата закр счета\'",
            "ТипСчета as \'Тип счета\'",
            "Задолжности as \'Задолжности\'",
            "ЛицСчета as \'Лиц счета\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'",
            "ОткрытиеСчета as \'Открытие счета\'",
            "ОткрытиеСчета.ВидВалюты as \'Вид валюты\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Организация.Наименование",
            "ОткрытиеСчета.ВидВалюты",
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("ЗакрытиеСчетаE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ЗакрытиеСчетаE", "ОткрытиеСчета", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ВидВалюты")]
    [MasterViewDefineAttribute("ЗакрытиеСчетаE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ЗакрытиеСчетаL", new string[] {
            "ДатаЗакрСчета as \'Дата закр счета\'",
            "ТипСчета as \'Тип счета\'",
            "Задолжности as \'Задолжности\'",
            "ЛицСчета as \'Лиц счета\'",
            "Организация.Наименование as \'Наименование\'",
            "ОткрытиеСчета.ВидВалюты as \'Вид валюты\'",
            "Сотрудники.IDСотрудн"})]
    public class ЗакрытиеСчета : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаЗакрСчета;
        
        private IIS.Operacionnoe_podrazdelenie.ТипСчета fТипСчета;
        
        private bool fЗадолжности;
        
        private int fЛицСчета;
        
        private IIS.Operacionnoe_podrazdelenie.Организация fОрганизация;
        
        private IIS.Operacionnoe_podrazdelenie.ОткрытиеСчета fОткрытиеСчета;
        
        private IIS.Operacionnoe_podrazdelenie.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ЗакрытиеСчета CustomMembers)

        // *** End programmer edit section *** (ЗакрытиеСчета CustomMembers)

        
        /// <summary>
        /// ДатаЗакрСчета.
        /// </summary>
        // *** Start programmer edit section *** (ЗакрытиеСчета.ДатаЗакрСчета CustomAttributes)

        // *** End programmer edit section *** (ЗакрытиеСчета.ДатаЗакрСчета CustomAttributes)
        public virtual System.DateTime ДатаЗакрСчета
        {
            get
            {
                // *** Start programmer edit section *** (ЗакрытиеСчета.ДатаЗакрСчета Get start)

                // *** End programmer edit section *** (ЗакрытиеСчета.ДатаЗакрСчета Get start)
                System.DateTime result = this.fДатаЗакрСчета;
                // *** Start programmer edit section *** (ЗакрытиеСчета.ДатаЗакрСчета Get end)

                // *** End programmer edit section *** (ЗакрытиеСчета.ДатаЗакрСчета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗакрытиеСчета.ДатаЗакрСчета Set start)

                // *** End programmer edit section *** (ЗакрытиеСчета.ДатаЗакрСчета Set start)
                this.fДатаЗакрСчета = value;
                // *** Start programmer edit section *** (ЗакрытиеСчета.ДатаЗакрСчета Set end)

                // *** End programmer edit section *** (ЗакрытиеСчета.ДатаЗакрСчета Set end)
            }
        }
        
        /// <summary>
        /// Задолжности.
        /// </summary>
        // *** Start programmer edit section *** (ЗакрытиеСчета.Задолжности CustomAttributes)

        // *** End programmer edit section *** (ЗакрытиеСчета.Задолжности CustomAttributes)
        public virtual bool Задолжности
        {
            get
            {
                // *** Start programmer edit section *** (ЗакрытиеСчета.Задолжности Get start)

                // *** End programmer edit section *** (ЗакрытиеСчета.Задолжности Get start)
                bool result = this.fЗадолжности;
                // *** Start programmer edit section *** (ЗакрытиеСчета.Задолжности Get end)

                // *** End programmer edit section *** (ЗакрытиеСчета.Задолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗакрытиеСчета.Задолжности Set start)

                // *** End programmer edit section *** (ЗакрытиеСчета.Задолжности Set start)
                this.fЗадолжности = value;
                // *** Start programmer edit section *** (ЗакрытиеСчета.Задолжности Set end)

                // *** End programmer edit section *** (ЗакрытиеСчета.Задолжности Set end)
            }
        }
        
        /// <summary>
        /// ЛицСчета.
        /// </summary>
        // *** Start programmer edit section *** (ЗакрытиеСчета.ЛицСчета CustomAttributes)

        // *** End programmer edit section *** (ЗакрытиеСчета.ЛицСчета CustomAttributes)
        public virtual int ЛицСчета
        {
            get
            {
                // *** Start programmer edit section *** (ЗакрытиеСчета.ЛицСчета Get start)

                // *** End programmer edit section *** (ЗакрытиеСчета.ЛицСчета Get start)
                int result = this.fЛицСчета;
                // *** Start programmer edit section *** (ЗакрытиеСчета.ЛицСчета Get end)

                // *** End programmer edit section *** (ЗакрытиеСчета.ЛицСчета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗакрытиеСчета.ЛицСчета Set start)

                // *** End programmer edit section *** (ЗакрытиеСчета.ЛицСчета Set start)
                this.fЛицСчета = value;
                // *** Start programmer edit section *** (ЗакрытиеСчета.ЛицСчета Set end)

                // *** End programmer edit section *** (ЗакрытиеСчета.ЛицСчета Set end)
            }
        }
        
        /// <summary>
        /// ТипСчета.
        /// </summary>
        // *** Start programmer edit section *** (ЗакрытиеСчета.ТипСчета CustomAttributes)

        // *** End programmer edit section *** (ЗакрытиеСчета.ТипСчета CustomAttributes)
        public virtual IIS.Operacionnoe_podrazdelenie.ТипСчета ТипСчета
        {
            get
            {
                // *** Start programmer edit section *** (ЗакрытиеСчета.ТипСчета Get start)

                // *** End programmer edit section *** (ЗакрытиеСчета.ТипСчета Get start)
                IIS.Operacionnoe_podrazdelenie.ТипСчета result = this.fТипСчета;
                // *** Start programmer edit section *** (ЗакрытиеСчета.ТипСчета Get end)

                // *** End programmer edit section *** (ЗакрытиеСчета.ТипСчета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗакрытиеСчета.ТипСчета Set start)

                // *** End programmer edit section *** (ЗакрытиеСчета.ТипСчета Set start)
                this.fТипСчета = value;
                // *** Start programmer edit section *** (ЗакрытиеСчета.ТипСчета Set end)

                // *** End programmer edit section *** (ЗакрытиеСчета.ТипСчета Set end)
            }
        }
        
        /// <summary>
        /// Закрытие счета.
        /// </summary>
        // *** Start programmer edit section *** (ЗакрытиеСчета.Организация CustomAttributes)

        // *** End programmer edit section *** (ЗакрытиеСчета.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Operacionnoe_podrazdelenie.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ЗакрытиеСчета.Организация Get start)

                // *** End programmer edit section *** (ЗакрытиеСчета.Организация Get start)
                IIS.Operacionnoe_podrazdelenie.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ЗакрытиеСчета.Организация Get end)

                // *** End programmer edit section *** (ЗакрытиеСчета.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗакрытиеСчета.Организация Set start)

                // *** End programmer edit section *** (ЗакрытиеСчета.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ЗакрытиеСчета.Организация Set end)

                // *** End programmer edit section *** (ЗакрытиеСчета.Организация Set end)
            }
        }
        
        /// <summary>
        /// Закрытие счета.
        /// </summary>
        // *** Start programmer edit section *** (ЗакрытиеСчета.ОткрытиеСчета CustomAttributes)

        // *** End programmer edit section *** (ЗакрытиеСчета.ОткрытиеСчета CustomAttributes)
        [PropertyStorage(new string[] {
                "ОткрытиеСчета"})]
        [NotNull()]
        public virtual IIS.Operacionnoe_podrazdelenie.ОткрытиеСчета ОткрытиеСчета
        {
            get
            {
                // *** Start programmer edit section *** (ЗакрытиеСчета.ОткрытиеСчета Get start)

                // *** End programmer edit section *** (ЗакрытиеСчета.ОткрытиеСчета Get start)
                IIS.Operacionnoe_podrazdelenie.ОткрытиеСчета result = this.fОткрытиеСчета;
                // *** Start programmer edit section *** (ЗакрытиеСчета.ОткрытиеСчета Get end)

                // *** End programmer edit section *** (ЗакрытиеСчета.ОткрытиеСчета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗакрытиеСчета.ОткрытиеСчета Set start)

                // *** End programmer edit section *** (ЗакрытиеСчета.ОткрытиеСчета Set start)
                this.fОткрытиеСчета = value;
                // *** Start programmer edit section *** (ЗакрытиеСчета.ОткрытиеСчета Set end)

                // *** End programmer edit section *** (ЗакрытиеСчета.ОткрытиеСчета Set end)
            }
        }
        
        /// <summary>
        /// Закрытие счета.
        /// </summary>
        // *** Start programmer edit section *** (ЗакрытиеСчета.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ЗакрытиеСчета.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Operacionnoe_podrazdelenie.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ЗакрытиеСчета.Сотрудники Get start)

                // *** End programmer edit section *** (ЗакрытиеСчета.Сотрудники Get start)
                IIS.Operacionnoe_podrazdelenie.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ЗакрытиеСчета.Сотрудники Get end)

                // *** End programmer edit section *** (ЗакрытиеСчета.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗакрытиеСчета.Сотрудники Set start)

                // *** End programmer edit section *** (ЗакрытиеСчета.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ЗакрытиеСчета.Сотрудники Set end)

                // *** End programmer edit section *** (ЗакрытиеСчета.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗакрытиеСчетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗакрытиеСчетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗакрытиеСчетаE", typeof(IIS.Operacionnoe_podrazdelenie.ЗакрытиеСчета));
                }
            }
            
            /// <summary>
            /// "ЗакрытиеСчетаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗакрытиеСчетаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗакрытиеСчетаL", typeof(IIS.Operacionnoe_podrazdelenie.ЗакрытиеСчета));
                }
            }
        }
    }
}
