//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Operacionnoe_podrazdelenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Открытие счета.
    /// </summary>
    // *** Start programmer edit section *** (ОткрытиеСчета CustomAttributes)

    // *** End programmer edit section *** (ОткрытиеСчета CustomAttributes)
    [AutoAltered()]
    [Caption("Открытие счета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОткрытиеСчетаE", new string[] {
            "ДатаОткрСчета as \'Дата откр счета\'",
            "ТипСчета as \'Тип счета\'",
            "ВидВалюты as \'Вид валюты\'",
            "ДокНаОткрСчета as \'Док на откр счета\'",
            "ЛицСчета as \'Лиц счета\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Организация.Наименование",
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("ОткрытиеСчетаE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ОткрытиеСчетаE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОткрытиеСчетаL", new string[] {
            "ДатаОткрСчета as \'Дата откр счета\'",
            "ТипСчета as \'Тип счета\'",
            "ВидВалюты as \'Вид валюты\'",
            "ДокНаОткрСчета as \'Док на откр счета\'",
            "ЛицСчета as \'Лиц счета\'",
            "Организация.Наименование as \'Наименование\'",
            "Сотрудники.IDСотрудн as \'Сотрудник\'"})]
    public class ОткрытиеСчета : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаОткрСчета;
        
        private IIS.Operacionnoe_podrazdelenie.ТипСчета fТипСчета;
        
        private string fВидВалюты;
        
        private bool fДокНаОткрСчета;
        
        private int fЛицСчета;
        
        private IIS.Operacionnoe_podrazdelenie.Организация fОрганизация;
        
        private IIS.Operacionnoe_podrazdelenie.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ОткрытиеСчета CustomMembers)

        // *** End programmer edit section *** (ОткрытиеСчета CustomMembers)

        
        /// <summary>
        /// ВидВалюты.
        /// </summary>
        // *** Start programmer edit section *** (ОткрытиеСчета.ВидВалюты CustomAttributes)

        // *** End programmer edit section *** (ОткрытиеСчета.ВидВалюты CustomAttributes)
        [StrLen(255)]
        public virtual string ВидВалюты
        {
            get
            {
                // *** Start programmer edit section *** (ОткрытиеСчета.ВидВалюты Get start)

                // *** End programmer edit section *** (ОткрытиеСчета.ВидВалюты Get start)
                string result = this.fВидВалюты;
                // *** Start programmer edit section *** (ОткрытиеСчета.ВидВалюты Get end)

                // *** End programmer edit section *** (ОткрытиеСчета.ВидВалюты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОткрытиеСчета.ВидВалюты Set start)

                // *** End programmer edit section *** (ОткрытиеСчета.ВидВалюты Set start)
                this.fВидВалюты = value;
                // *** Start programmer edit section *** (ОткрытиеСчета.ВидВалюты Set end)

                // *** End programmer edit section *** (ОткрытиеСчета.ВидВалюты Set end)
            }
        }
        
        /// <summary>
        /// ДатаОткрСчета.
        /// </summary>
        // *** Start programmer edit section *** (ОткрытиеСчета.ДатаОткрСчета CustomAttributes)

        // *** End programmer edit section *** (ОткрытиеСчета.ДатаОткрСчета CustomAttributes)
        public virtual System.DateTime ДатаОткрСчета
        {
            get
            {
                // *** Start programmer edit section *** (ОткрытиеСчета.ДатаОткрСчета Get start)

                // *** End programmer edit section *** (ОткрытиеСчета.ДатаОткрСчета Get start)
                System.DateTime result = this.fДатаОткрСчета;
                // *** Start programmer edit section *** (ОткрытиеСчета.ДатаОткрСчета Get end)

                // *** End programmer edit section *** (ОткрытиеСчета.ДатаОткрСчета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОткрытиеСчета.ДатаОткрСчета Set start)

                // *** End programmer edit section *** (ОткрытиеСчета.ДатаОткрСчета Set start)
                this.fДатаОткрСчета = value;
                // *** Start programmer edit section *** (ОткрытиеСчета.ДатаОткрСчета Set end)

                // *** End programmer edit section *** (ОткрытиеСчета.ДатаОткрСчета Set end)
            }
        }
        
        /// <summary>
        /// ДокНаОткрСчета.
        /// </summary>
        // *** Start programmer edit section *** (ОткрытиеСчета.ДокНаОткрСчета CustomAttributes)

        // *** End programmer edit section *** (ОткрытиеСчета.ДокНаОткрСчета CustomAttributes)
        public virtual bool ДокНаОткрСчета
        {
            get
            {
                // *** Start programmer edit section *** (ОткрытиеСчета.ДокНаОткрСчета Get start)

                // *** End programmer edit section *** (ОткрытиеСчета.ДокНаОткрСчета Get start)
                bool result = this.fДокНаОткрСчета;
                // *** Start programmer edit section *** (ОткрытиеСчета.ДокНаОткрСчета Get end)

                // *** End programmer edit section *** (ОткрытиеСчета.ДокНаОткрСчета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОткрытиеСчета.ДокНаОткрСчета Set start)

                // *** End programmer edit section *** (ОткрытиеСчета.ДокНаОткрСчета Set start)
                this.fДокНаОткрСчета = value;
                // *** Start programmer edit section *** (ОткрытиеСчета.ДокНаОткрСчета Set end)

                // *** End programmer edit section *** (ОткрытиеСчета.ДокНаОткрСчета Set end)
            }
        }
        
        /// <summary>
        /// ЛицСчета.
        /// </summary>
        // *** Start programmer edit section *** (ОткрытиеСчета.ЛицСчета CustomAttributes)

        // *** End programmer edit section *** (ОткрытиеСчета.ЛицСчета CustomAttributes)
        public virtual int ЛицСчета
        {
            get
            {
                // *** Start programmer edit section *** (ОткрытиеСчета.ЛицСчета Get start)

                // *** End programmer edit section *** (ОткрытиеСчета.ЛицСчета Get start)
                int result = this.fЛицСчета;
                // *** Start programmer edit section *** (ОткрытиеСчета.ЛицСчета Get end)

                // *** End programmer edit section *** (ОткрытиеСчета.ЛицСчета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОткрытиеСчета.ЛицСчета Set start)

                // *** End programmer edit section *** (ОткрытиеСчета.ЛицСчета Set start)
                this.fЛицСчета = value;
                // *** Start programmer edit section *** (ОткрытиеСчета.ЛицСчета Set end)

                // *** End programmer edit section *** (ОткрытиеСчета.ЛицСчета Set end)
            }
        }
        
        /// <summary>
        /// ТипСчета.
        /// </summary>
        // *** Start programmer edit section *** (ОткрытиеСчета.ТипСчета CustomAttributes)

        // *** End programmer edit section *** (ОткрытиеСчета.ТипСчета CustomAttributes)
        public virtual IIS.Operacionnoe_podrazdelenie.ТипСчета ТипСчета
        {
            get
            {
                // *** Start programmer edit section *** (ОткрытиеСчета.ТипСчета Get start)

                // *** End programmer edit section *** (ОткрытиеСчета.ТипСчета Get start)
                IIS.Operacionnoe_podrazdelenie.ТипСчета result = this.fТипСчета;
                // *** Start programmer edit section *** (ОткрытиеСчета.ТипСчета Get end)

                // *** End programmer edit section *** (ОткрытиеСчета.ТипСчета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОткрытиеСчета.ТипСчета Set start)

                // *** End programmer edit section *** (ОткрытиеСчета.ТипСчета Set start)
                this.fТипСчета = value;
                // *** Start programmer edit section *** (ОткрытиеСчета.ТипСчета Set end)

                // *** End programmer edit section *** (ОткрытиеСчета.ТипСчета Set end)
            }
        }
        
        /// <summary>
        /// Открытие счета.
        /// </summary>
        // *** Start programmer edit section *** (ОткрытиеСчета.Организация CustomAttributes)

        // *** End programmer edit section *** (ОткрытиеСчета.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Operacionnoe_podrazdelenie.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ОткрытиеСчета.Организация Get start)

                // *** End programmer edit section *** (ОткрытиеСчета.Организация Get start)
                IIS.Operacionnoe_podrazdelenie.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ОткрытиеСчета.Организация Get end)

                // *** End programmer edit section *** (ОткрытиеСчета.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОткрытиеСчета.Организация Set start)

                // *** End programmer edit section *** (ОткрытиеСчета.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ОткрытиеСчета.Организация Set end)

                // *** End programmer edit section *** (ОткрытиеСчета.Организация Set end)
            }
        }
        
        /// <summary>
        /// Открытие счета.
        /// </summary>
        // *** Start programmer edit section *** (ОткрытиеСчета.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ОткрытиеСчета.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Operacionnoe_podrazdelenie.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ОткрытиеСчета.Сотрудники Get start)

                // *** End programmer edit section *** (ОткрытиеСчета.Сотрудники Get start)
                IIS.Operacionnoe_podrazdelenie.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ОткрытиеСчета.Сотрудники Get end)

                // *** End programmer edit section *** (ОткрытиеСчета.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОткрытиеСчета.Сотрудники Set start)

                // *** End programmer edit section *** (ОткрытиеСчета.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ОткрытиеСчета.Сотрудники Set end)

                // *** End programmer edit section *** (ОткрытиеСчета.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОткрытиеСчетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОткрытиеСчетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОткрытиеСчетаE", typeof(IIS.Operacionnoe_podrazdelenie.ОткрытиеСчета));
                }
            }
            
            /// <summary>
            /// "ОткрытиеСчетаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОткрытиеСчетаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОткрытиеСчетаL", typeof(IIS.Operacionnoe_podrazdelenie.ОткрытиеСчета));
                }
            }
        }
    }
}
