//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Operacionnoe_podrazdelenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отдел опер подр.
    /// </summary>
    // *** Start programmer edit section *** (ОтделОперПодр CustomAttributes)

    // *** End programmer edit section *** (ОтделОперПодр CustomAttributes)
    [AutoAltered()]
    [Caption("Отдел опер подр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтделОперПодрE", new string[] {
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("ОтделОперПодрE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОтделОперПодрL", new string[] {
            "Сотрудники.IDСотрудн"})]
    public class ОтделОперПодр : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Operacionnoe_podrazdelenie.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ОтделОперПодр CustomMembers)

        // *** End programmer edit section *** (ОтделОперПодр CustomMembers)

        
        /// <summary>
        /// Отдел опер подр.
        /// </summary>
        // *** Start programmer edit section *** (ОтделОперПодр.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ОтделОперПодр.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Operacionnoe_podrazdelenie.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ОтделОперПодр.Сотрудники Get start)

                // *** End programmer edit section *** (ОтделОперПодр.Сотрудники Get start)
                IIS.Operacionnoe_podrazdelenie.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ОтделОперПодр.Сотрудники Get end)

                // *** End programmer edit section *** (ОтделОперПодр.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтделОперПодр.Сотрудники Set start)

                // *** End programmer edit section *** (ОтделОперПодр.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ОтделОперПодр.Сотрудники Set end)

                // *** End programmer edit section *** (ОтделОперПодр.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтделОперПодрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтделОперПодрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтделОперПодрE", typeof(IIS.Operacionnoe_podrazdelenie.ОтделОперПодр));
                }
            }
            
            /// <summary>
            /// "ОтделОперПодрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтделОперПодрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтделОперПодрL", typeof(IIS.Operacionnoe_podrazdelenie.ОтделОперПодр));
                }
            }
        }
    }
}
