//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Operacionnoe_podrazdelenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип счета.
    /// </summary>
    // *** Start programmer edit section *** (ТипСчета CustomAttributes)

    // *** End programmer edit section *** (ТипСчета CustomAttributes)
    public enum ТипСчета
    {
        
        // *** Start programmer edit section *** (ТипСчета.Текущий CustomAttributes)

        // *** End programmer edit section *** (ТипСчета.Текущий CustomAttributes)
        [Caption("Текущий")]
        Текущий,
        
        // *** Start programmer edit section *** (ТипСчета.Расчетный CustomAttributes)

        // *** End programmer edit section *** (ТипСчета.Расчетный CustomAttributes)
        [Caption("Расчетный")]
        Расчетный,
        
        // *** Start programmer edit section *** (ТипСчета.Бюджетный CustomAttributes)

        // *** End programmer edit section *** (ТипСчета.Бюджетный CustomAttributes)
        [Caption("Бюджетный")]
        Бюджетный,
        
        // *** Start programmer edit section *** (ТипСчета.Депозитный CustomAttributes)

        // *** End programmer edit section *** (ТипСчета.Депозитный CustomAttributes)
        [Caption("Депозитный")]
        Депозитный,
        
        // *** Start programmer edit section *** (ТипСчета.Специальный CustomAttributes)

        // *** End programmer edit section *** (ТипСчета.Специальный CustomAttributes)
        [Caption("Специальный")]
        Специальный,
        
        // *** Start programmer edit section *** (ТипСчета.Валютный CustomAttributes)

        // *** End programmer edit section *** (ТипСчета.Валютный CustomAttributes)
        [Caption("Валютный")]
        Валютный,
        
        // *** Start programmer edit section *** (ТипСчета.СчетПоВкладам CustomAttributes)

        // *** End programmer edit section *** (ТипСчета.СчетПоВкладам CustomAttributes)
        [Caption("Счет по вкладам")]
        СчетПоВкладам,
    }
}
