//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Operacionnoe_podrazdelenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Формир досье.
    /// </summary>
    // *** Start programmer edit section *** (ФормирДосье CustomAttributes)

    // *** End programmer edit section *** (ФормирДосье CustomAttributes)
    [AutoAltered()]
    [Caption("Формир досье")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормирДосьеE", new string[] {
            "НаименДосье as \'Наимен досье\'",
            "ДатаОформл as \'Дата оформл\'",
            "Договора as \'Договора\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Клиенты as \'Клиенты\'",
            "Клиенты.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Организация.Наименование",
            "Сотрудники.ФИО",
            "Клиенты.ФИО"})]
    [MasterViewDefineAttribute("ФормирДосьеE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ФормирДосьеE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ФормирДосьеE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ФормирДосьеL", new string[] {
            "НаименДосье as \'Наименование досье\'",
            "ДатаОформл as \'Дата оформления\'",
            "Договора as \'№ Договора\'",
            "Организация.Наименование as \'Организация\'",
            "Клиенты.IDКлиента as \'ID клиента\'",
            "Сотрудники.IDСотрудн as \'ID сотрудника\'"})]
    public class ФормирДосье : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименДосье;
        
        private System.DateTime fДатаОформл;
        
        private int fДоговора;
        
        private IIS.Operacionnoe_podrazdelenie.Организация fОрганизация;
        
        private IIS.Operacionnoe_podrazdelenie.Сотрудники fСотрудники;
        
        private IIS.Operacionnoe_podrazdelenie.Клиенты fКлиенты;
        
        // *** Start programmer edit section *** (ФормирДосье CustomMembers)

        // *** End programmer edit section *** (ФормирДосье CustomMembers)

        
        /// <summary>
        /// ДатаОформл.
        /// </summary>
        // *** Start programmer edit section *** (ФормирДосье.ДатаОформл CustomAttributes)

        // *** End programmer edit section *** (ФормирДосье.ДатаОформл CustomAttributes)
        public virtual System.DateTime ДатаОформл
        {
            get
            {
                // *** Start programmer edit section *** (ФормирДосье.ДатаОформл Get start)

                // *** End programmer edit section *** (ФормирДосье.ДатаОформл Get start)
                System.DateTime result = this.fДатаОформл;
                // *** Start programmer edit section *** (ФормирДосье.ДатаОформл Get end)

                // *** End programmer edit section *** (ФормирДосье.ДатаОформл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирДосье.ДатаОформл Set start)

                // *** End programmer edit section *** (ФормирДосье.ДатаОформл Set start)
                this.fДатаОформл = value;
                // *** Start programmer edit section *** (ФормирДосье.ДатаОформл Set end)

                // *** End programmer edit section *** (ФормирДосье.ДатаОформл Set end)
            }
        }
        
        /// <summary>
        /// Договора.
        /// </summary>
        // *** Start programmer edit section *** (ФормирДосье.Договора CustomAttributes)

        // *** End programmer edit section *** (ФормирДосье.Договора CustomAttributes)
        public virtual int Договора
        {
            get
            {
                // *** Start programmer edit section *** (ФормирДосье.Договора Get start)

                // *** End programmer edit section *** (ФормирДосье.Договора Get start)
                int result = this.fДоговора;
                // *** Start programmer edit section *** (ФормирДосье.Договора Get end)

                // *** End programmer edit section *** (ФормирДосье.Договора Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирДосье.Договора Set start)

                // *** End programmer edit section *** (ФормирДосье.Договора Set start)
                this.fДоговора = value;
                // *** Start programmer edit section *** (ФормирДосье.Договора Set end)

                // *** End programmer edit section *** (ФормирДосье.Договора Set end)
            }
        }
        
        /// <summary>
        /// НаименДосье.
        /// </summary>
        // *** Start programmer edit section *** (ФормирДосье.НаименДосье CustomAttributes)

        // *** End programmer edit section *** (ФормирДосье.НаименДосье CustomAttributes)
        [StrLen(255)]
        public virtual string НаименДосье
        {
            get
            {
                // *** Start programmer edit section *** (ФормирДосье.НаименДосье Get start)

                // *** End programmer edit section *** (ФормирДосье.НаименДосье Get start)
                string result = this.fНаименДосье;
                // *** Start programmer edit section *** (ФормирДосье.НаименДосье Get end)

                // *** End programmer edit section *** (ФормирДосье.НаименДосье Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирДосье.НаименДосье Set start)

                // *** End programmer edit section *** (ФормирДосье.НаименДосье Set start)
                this.fНаименДосье = value;
                // *** Start programmer edit section *** (ФормирДосье.НаименДосье Set end)

                // *** End programmer edit section *** (ФормирДосье.НаименДосье Set end)
            }
        }
        
        /// <summary>
        /// Формир досье.
        /// </summary>
        // *** Start programmer edit section *** (ФормирДосье.Клиенты CustomAttributes)

        // *** End programmer edit section *** (ФормирДосье.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Operacionnoe_podrazdelenie.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (ФормирДосье.Клиенты Get start)

                // *** End programmer edit section *** (ФормирДосье.Клиенты Get start)
                IIS.Operacionnoe_podrazdelenie.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (ФормирДосье.Клиенты Get end)

                // *** End programmer edit section *** (ФормирДосье.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирДосье.Клиенты Set start)

                // *** End programmer edit section *** (ФормирДосье.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (ФормирДосье.Клиенты Set end)

                // *** End programmer edit section *** (ФормирДосье.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Формир досье.
        /// </summary>
        // *** Start programmer edit section *** (ФормирДосье.Организация CustomAttributes)

        // *** End programmer edit section *** (ФормирДосье.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Operacionnoe_podrazdelenie.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ФормирДосье.Организация Get start)

                // *** End programmer edit section *** (ФормирДосье.Организация Get start)
                IIS.Operacionnoe_podrazdelenie.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ФормирДосье.Организация Get end)

                // *** End programmer edit section *** (ФормирДосье.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирДосье.Организация Set start)

                // *** End programmer edit section *** (ФормирДосье.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ФормирДосье.Организация Set end)

                // *** End programmer edit section *** (ФормирДосье.Организация Set end)
            }
        }
        
        /// <summary>
        /// Формир досье.
        /// </summary>
        // *** Start programmer edit section *** (ФормирДосье.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ФормирДосье.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Operacionnoe_podrazdelenie.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ФормирДосье.Сотрудники Get start)

                // *** End programmer edit section *** (ФормирДосье.Сотрудники Get start)
                IIS.Operacionnoe_podrazdelenie.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ФормирДосье.Сотрудники Get end)

                // *** End programmer edit section *** (ФормирДосье.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирДосье.Сотрудники Set start)

                // *** End programmer edit section *** (ФормирДосье.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ФормирДосье.Сотрудники Set end)

                // *** End programmer edit section *** (ФормирДосье.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормирДосьеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирДосьеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирДосьеE", typeof(IIS.Operacionnoe_podrazdelenie.ФормирДосье));
                }
            }
            
            /// <summary>
            /// "ФормирДосьеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирДосьеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирДосьеL", typeof(IIS.Operacionnoe_podrazdelenie.ФормирДосье));
                }
            }
        }
    }
}
