import IISOperacionnoe_podrazdelenieОтделОперПодрEController from '../i-i-s-operacionnoe-podrazdelenie-отдел-опер-подр-e';

var IISOperacionnoe_podrazdelenieОтделОперПодрENewController = IISOperacionnoe_podrazdelenieОтделОперПодрEController;
export default IISOperacionnoe_podrazdelenieОтделОперПодрENewController;
