import IISOperacionnoe_podrazdelenieФормирДосьеEController from '../i-i-s-operacionnoe-podrazdelenie-формир-досье-e';

var IISOperacionnoe_podrazdelenieФормирДосьеENewController = IISOperacionnoe_podrazdelenieФормирДосьеEController;
export default IISOperacionnoe_podrazdelenieФормирДосьеENewController;
